version: '3.7'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - /mnt/docker-cluster/zigbee2mqtt/data:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
    deploy:
      placement:
        constraints: [node.hostname == rpi-3]
      replicas: 1
